/// A Flutter package for applying color tints to images while preserving detail.
///
/// This library provides utilities to colorize images using color matrix
/// transformations that maintain the original image's luminance and detail.
library;

import 'package:flutter/widgets.dart';

/// Builds a color matrix for applying a color tint to an image while
/// preserving its details and luminance information.
///
/// This function creates a 5x4 color matrix (represented as a flat list of 20 values)
/// that can be used with [ColorFilter.matrix] to tint an image. The matrix preserves
/// the image's luminance (brightness) while applying the specified color.
///
/// The transformation works by:
/// 1. Converting the input color to RGB values (0.0-1.0 range)
/// 2. Applying an intensity multiplier for more vivid colors
/// 3. Multiplying each color channel by the standard luminance weights
///    (Red: 0.299, Green: 0.587, Blue: 0.114)
///
/// Example:
/// ```dart
/// final matrix = buildColorMatrix(Colors.blue);
/// final colorFilter = ColorFilter.matrix(matrix);
/// ```
///
/// Parameters:
/// - [color]: The target color to apply to the image
///
/// Returns a list of 20 doubles representing a 5x4 color matrix.
List<double> buildColorMatrix(Color color) {
  // Standard luminance weights for RGB channels
  // These values represent how the human eye perceives brightness
  const luminanceR = 0.299;
  const luminanceG = 0.587;
  const luminanceB = 0.114;

  // Intensity multiplier to make colors more vivid
  // Values > 1.0 increase color saturation
  const intensity = 1.8;

  // Convert color channels to 0.0-1.0 range and apply intensity
  final r = ((color.r * 255.0).round().clamp(0, 255) / 255 * intensity).clamp(0.0, 1.0);
  final g = ((color.g * 255.0).round().clamp(0, 255) / 255 * intensity).clamp(0.0, 1.0);
  final b = ((color.b * 255.0).round().clamp(0, 255) / 255 * intensity).clamp(0.0, 1.0);

  // Build the 5x4 color matrix
  // Matrix format: [R, G, B, A, offset] for each output channel
  return [
    // Red output = luminance * red component
    luminanceR * r, luminanceG * r, luminanceB * r, 0, 0,
    // Green output = luminance * green component
    luminanceR * g, luminanceG * g, luminanceB * g, 0, 0,
    // Blue output = luminance * blue component
    luminanceR * b, luminanceG * b, luminanceB * b, 0, 0,
    // Alpha output = unchanged
    0, 0, 0, 1, 0,
  ];
}

/// A widget that applies a color tint to its child image while preserving details.
///
/// This widget wraps a [ColorFiltered] widget with a color matrix generated by
/// [buildColorMatrix]. It's particularly useful for applying brand colors or
/// theme colors to monochrome icons and images.
///
/// The color transformation preserves the luminance (brightness detail) of the
/// original image while applying the specified color tint.
///
/// Example:
/// ```dart
/// ColoredImage(
///   color: Colors.blue,
///   child: Image.asset('assets/icon.png'),
/// )
/// ```
class ColoredImage extends StatelessWidget {
  /// Creates a colored image widget.
  ///
  /// The [color] and [child] parameters must not be null.
  const ColoredImage({
    super.key,
    required this.color,
    required this.child,
    this.blendMode = BlendMode.srcATop,
  });

  /// The color to apply to the child image.
  final Color color;

  /// The image widget to be colored.
  final Widget child;

  /// The blend mode to use when applying the color filter.
  ///
  /// Defaults to [BlendMode.srcATop] which works well for most cases.
  final BlendMode blendMode;

  @override
  Widget build(BuildContext context) {
    return ColorFiltered(
      colorFilter: ColorFilter.matrix(buildColorMatrix(color)),
      child: child,
    );
  }
}

/// A widget that applies a color tint to its child while preserving details.
///
/// Unlike [ColoredImage], this widget can be used with any child widget,
/// not just images. It's useful for applying color effects to complex
/// widget trees.
///
/// Example:
/// ```dart
/// ColorTintFilter(
///   color: Colors.purple,
///   child: Column(
///     children: [
///       Image.asset('assets/image1.png'),
///       Image.asset('assets/image2.png'),
///     ],
///   ),
/// )
/// ```
class ColorTintFilter extends StatelessWidget {
  /// Creates a color tint filter widget.
  ///
  /// The [color] and [child] parameters must not be null.
  const ColorTintFilter({
    super.key,
    required this.color,
    required this.child,
  });

  /// The color to apply as a tint.
  final Color color;

  /// The widget to apply the color tint to.
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return ColorFiltered(
      colorFilter: ColorFilter.matrix(buildColorMatrix(color)),
      child: child,
    );
  }
}
